<?php

namespace App\Models;

abstract class BaseModel extends \Illuminate\Database\Eloquent\Model
{
    public function formatDate(string $field, string $format = 'H:i:s d.m.Y'): string
    {
        return date($format, strtotime($this->$field));
    }

    public function getCreatedAtFormatted(): string
    {
        return $this->formatDate('created_at');
    }

    public function getUpdatedAtFormatted(): string
    {
        return $this->formatDate('updated_at');
    }

    public function getDeletedAtFormatted(): string
    {
        return $this->formatDate('deleted_at');
    }

    public function __get($key)
    {
        return parent::__get($key); // TODO: Change the autogenerated stub
    }
}
